### ISSUE TITLE
AttributeError on decorator without name attribute

### ISSUE THREAD

**Issue by fniessink** [fcfangcc/pylint-pydantic#1]
Running Pylint 2.8.2 with the pylint-pydantic plugin 0.1.2 gives me this exception:

```
Exception on node <FunctionDef.login l.117 at 0x112fb2b50> in file '/Users/fniessink/Developer/quality-time/components/server/src/routes/auth.py'
Traceback (most recent call last):
  File "/Users/fniessink/Developer/quality-time/components/server/venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint/lint/run.py", line 381, in __init__
    linter.check(args)
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 873, in check
    self._check_files(
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 907, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 933, in _check_file
    check_astroid_module(ast_node)
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1067, in check_astroid_module
    retval = self._check_astroid_module(
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1112, in _check_astroid_module
    walker.walk(ast_node)
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 77, in walk
    self.walk(child)
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 74, in walk
    callback(astroid)
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint_plugin_utils/__init__.py", line 55, in augment_func
    augmentation(chain, node)
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint_plugin_utils/__init__.py", line 144, in do_suppress
    if test_func(node):
  File "/Users/fniessink/Developer/quality-time/components/server/venv/lib/python3.9/site-packages/pylint_pydantic/__init__.py", line 19, in is_validator_method
    if isinstance(decorator, Call) and decorator.func.name in validator_method_names:
AttributeError: 'Attribute' object has no attribute 'name'
```

The relevant function definition is:

```python
@bottle.post("/api/v3/login", authentication_required=False)
def login(database: Database) -> dict[str, Union[bool, datetime, str]]:
    """Log the user in. Add credentials as JSON payload, e.g. {username: 'user', password: 'pass'}."""
    ...
```

The plugin expects all decorator.func to have a name attribute, but apparently that's not the case with bottle decorators.

**Comment by fcfangcc** [comment]
0.1.3 has fixed this problem
